### ISSUE TITLE
Tiny JSON C api

### ISSUE THREAD

**Issue by Phlosioneer** [BucknellSustainability/Flower#223]
Arduino is just a fancy form of C, so we can make the library in C and copy it over. We need a C program that has:

- [x] `int start_packet()` - Sets up a global structure to start making a JSON response.
- [x] `int add_int_field(const char* name, int value)` - Adds a number to the JSON response.
- [x] `int add_double_field(const char* name, double value, int decimal_places)` - Adds a number to the JSON response.
- [x] `int add_text_field(const char* name, const char* value)` - Adds a string to the JSON response.
- [x] `int end_packet()` - Sends the packet along the Serial connection.

For now, we'll just use printf to print out the packet, until we actually use an Arduino.

To test these, make a C program that prompts a user to input (1) an int, (2) a double, (3) a text field, or (4) finish the packet and print it out.

**Comment by BenMatase** [comment]
Please add an estimate to this

**Comment by DTV96Calibre** [comment]
This is now implemented in code and works.

**Comment by BenMatase** [comment]
Sweet. Throw up a PR
