### ISSUE TITLE
Create tutorial to connect Arduino to system

### ISSUE THREAD

**Issue by BenMatase** [BucknellSustainability/Flower#24]
This should be pretty easy to use and self-explanatory.  Having students with a non-technical background should be tested on

**Comment by BenMatase** [comment]
This can't really be worked on until we get a system together.  This could be converted to an epic later

**Comment by DTV96Calibre** [comment]
This has been partially resolved. A tutorial for connecting the arduino to a pi node and claiming the arduino through the web dashboard needs to be written.

**Comment by BenMatase** [comment]
Now that Dan has updated information, I believe this Arduino part is complete
