### ISSUE TITLE
Decide on how code upload is to be implemented

### ISSUE THREAD

**Issue by BenMatase** [BucknellSustainability/Flower#254]
We talked about a web interface to start, but need to talk more about further more complex interfaces.

**Comment by DTV96Calibre** [comment]
The current plan of action is to implement an upload feature in the project dashboard allowing users to upload precompiled hex files which are then deployed to a specified Arduino.

**Comment by BenMatase** [comment]
Sounds good. In future, we will look into an Arduino IDE plugin and in-browser code modifier.  For now we are keeping it simple

**Comment by BenMatase** [comment]
The flow will be: IDE compiles source into hex file which can be exported using the IDE, the user will need to upload the hex file on our dashboard, this will send the file to the server and an entry will be created in the DB to point to that hex file, the backend will add a row in a "code upload alert" table that Pis will be getting back if they are connected to the Arduino that needs to be code uploaded, the Pi will check to see if it needs to grab the file every time it inserts data (often/~1s), the hex file will be transferred to the Pi through a DB query, then uploaded to the correct Arduino through the command line upload interface
