### ISSUE TITLE
Research how to upload code to an Arduino without using the IDE

### ISSUE THREAD

**Issue by Phlosioneer** [BucknellSustainability/Flower#294]
@DTV96Calibre has done some preliminary research; apparently the IDE uses a command line utility called "avrdude" or something. We need to research the specifics.

**Comment by per1234** [comment]
1. (In the Arduino IDE) **File > Preferences > Show verbose output during: > upload (check) > OK**
2. Sketch > Upload

After the upload completes, examine the contents of the black console window at the bottom of the Arduino IDE window. You may need to scroll up to see the full contents. There you will find the upload command used by the Arduino IDE. You can run the same command from a command line or script.
