### ISSUE TITLE
Research Data Visualization JS Libraries

### ISSUE THREAD

**Issue by BenMatase** [BucknellSustainability/Flower#94]
Look at some different options and decide on one.  We talked about using Chart.js, but want to keep options open.  Maybe write up a small blurb about how to use it and some example code would be amazing.

**Comment by BenMatase** [comment]
I know you are at a conference, but if you have any free time, it would be awesome if you could do some research on this since you are the JS expert on the team.

**Comment by DTV96Calibre** [comment]
I found a library that can help us with developing an interactive map for accessing project pages.
[Polymaps](http://polymaps.org/)

**Comment by DTV96Calibre** [comment]
Dygraph and Chart.js are both good candidates. Dygraph supports zoom and pan without a plugin but Chart.js is prettier.

**Comment by BenMatase** [comment]
Marchiori's project that has similar use case to ours: http://www.eg.bucknell.edu/eswapp/index.html

**Comment by DTV96Calibre** [comment]
They're using Highcharts for their graphing. I looked into it just now and it's really really good. It'll be free for us to use so I'll be looking into getting a helloworld going.

**Comment by BenMatase** [comment]
I feel like research is done, I'm going to make a new task that is making first iteration
